### ISSUE TITLE
Reexamine Title mappings

### ISSUE THREAD

**Issue by amoeba** [amoeba/treestats.net#14]

**Comment by nygard** [comment]
See https://gist.github.com/nygard/2f072893d4edd437ce4f for a corrected title list.  The second file has the localized title names, but I don't have a mapping from the localized string identifiers (i.e. 0fd8a66c for Wandering Fool) to the titles, so that's mostly useful for checking the spelling.

Comparing with the titles in your wiki, 16-47 are wrong, and you are missing my 0x100-0x10f, 0x200-0x20f, and 0x300-0x30f from my list.

**Comment by amoeba** [comment]
This is awesome! Thanks Steve. I haven't had a chance to look at my script
(or do anything with TreeStats) but I suspect it'd be safe to just migrate
your values in. I'll get on this soon.
